export namespace KeyboardUtils {
  export const keyToNumber = (key: string) => {
    switch (key) {
      case 'q':
        return 0;
      case 'w':
        return 1;
      case 'e':
        return 2;
      case 'r':
        return 3;
      case 't':
        return 4;
      case 'y':
        return 5;
      case 'u':
        return 6;
      case 'i':
        return 7;
      case 'o':
        return 8;
      case 'p':
        return 9;
      case '[':
        return 10;
      case ']':
        return 11;
      case 'a':
        return 12;
      case 's':
        return 13;
      case 'd':
        return 14;
      case 'f':
        return 15;
      case 'g':
        return 16;
      case 'h':
        return 17;
      case 'j':
        return 18;
      case 'k':
        return 19;
      case 'l':
        return 20;
      case ';':
        return 21;
      case "'":
        return 23;
      case '\\':
        return 24;
      case '`':
        return 25;
      case 'z':
        return 26;
      case 'x':
        return 27;
      case 'c':
        return 28;
      case 'v':
        return 29;
      case 'b':
        return 30;
      case 'n':
        return 31;
      case 'm':
        return 32;
      case ',':
        return 33;
      case '.':
        return 34;
      case '/':
        return 35;
      default:
        return null;
    }
  };
  export const numberToKey = (num: number) => {
    switch (num) {
      case 0:
        return 'q';
      case 1:
        return 'w';
      case 2:
        return 'e';
      case 3:
        return 'r';
      case 4:
        return 't';
      case 5:
        return 'y';
      case 6:
        return 'u';
      case 7:
        return 'i';
      case 8:
        return 'o';
      case 9:
        return 'p';
      case 10:
        return '[';
      case 11:
        return ']';
      case 12:
        return 'a';
      case 13:
        return 's';
      case 14:
        return 'd';
      case 15:
        return 'f';
      case 16:
        return 'g';
      case 17:
        return 'h';
      case 18:
        return 'j';
      case 19:
        return 'k';
      case 20:
        return 'l';
      case 21:
        return ';';
      case 23:
        return "'";
      case 24:
        return '\\';
      case 25:
        return '`';
      case 26:
        return 'z';
      case 27:
        return 'x';
      case 28:
        return 'c';
      case 29:
        return 'v';
      case 30:
        return 'b';
      case 31:
        return 'n';
      case 32:
        return 'm';
      case 33:
        return ',';
      case 34:
        return '.';
      case 35:
        return '/';
      default:
        return null;
    }
  };
}
